Controllers/BlogController.cs
using LunarDev.Areas.Identity.Data;
using LunarDev.Data;
using LunarDev.Models;
using LunarDev;
using Markdig;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Html2Markdown;

namespace LunarDev.Controllers
{
    [Route("blog")]
    public class BlogController : Controller
    {
        private ILogger<BlogController> _logger;
        private AuthContext _authContext;
        private UserManager<AuthUser> _userManager;

        public BlogController(ILogger<BlogController> logger, AuthContext authContext, UserManager<AuthUser> userManager)
        {
            _logger = logger;
            _authContext = authContext;
            _userManager = userManager;
        }

        [Route("")]
        public IActionResult Index(int? page)
        {
            var date = DateTime.UtcNow;
            var blogs = _authContext.Blogs.Where(b =>
                (b.IsDraft == false) && (DateTime.Compare(b.PublishDate, date) <= 0))
                .ToList(); ;

            if (page == null)
            {
                page = 1;
            }

            int pageSize = 8;
            int pageNumber = (page ?? 1);

            return View(PaginatedList<BlogArticleModel>.Create(blogs, pageNumber, pageSize));
        }

        [Route("article/{slug}")]
        public async Task<IActionResult> ViewArticleAsync(string slug)
        {
            var article = _authContext.Blogs.FirstOrDefault(b => b.Slug == slug);

            article.Views++;
            _authContext.Blogs.Update(article);
            await _authContext.SaveChangesAsync();

            return View(article);
        }

        [Authorize(Policy = "StaffAccess")]
        [HttpGet]
        [Route("Admin/CreateArticle")]
        public IActionResult CreateArticle()
        {
            return View(new BlogArticleModel());
        }

        [Authorize(Policy = "StaffAccess")]
        [HttpPost]
        [Route("Admin/CreateArticle")]
        public async Task<IActionResult> CreateArticle(BlogArticleModel model)
        {
            BlogArticleModel article = new BlogArticleModel();
            if (ModelState.IsValid)
            {
                IFormFile file = Request.Form.Files.FirstOrDefault();
                using (var dataStream = new MemoryStream())
                {
                    await file.CopyToAsync(dataStream);
                    article.Thumbnail = dataStream.ToArray();
                }

                string htmlArticle = Markdown.ToHtml(model.Article);

                article.Title = model.Title;
                article.PublishDate = model.PublishDate;
                article.Article = htmlArticle;
                article.Description = model.Description;
                article.IsDraft = model.IsDraft;
                article.Slug = model.Slug;

                _authContext.Blogs.Add(article);
                await _authContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [Authorize(Policy = "StaffAccess")]
        [HttpGet]
        [Route("Admin/EditArticle")]
        public IActionResult EditArticle(int id)
        {
            var article = _authContext.Blogs.FirstOrDefault(b => b.Id == id);

            var converter = new Converter();
            article.Article = converter.Convert(article.Article);

            return View(article);
        }

        [Authorize(Policy = "StaffAccess")]
        [HttpPost]
        [Route("Admin/EditArticle")]
        public async Task<IActionResult> EditArticle(int id, BlogArticleModel model)
        {
            var article = await _authContext.Blogs.FirstOrDefaultAsync(b => b.Id == id);
            if (ModelState.IsValid)
            {
                if (Request.Form.Files.Count > 0)
                {
                    IFormFile file = Request.Form.Files.FirstOrDefault();
                    using (var dataStream = new MemoryStream())
                    {
                        await file.CopyToAsync(dataStream);
                        article.Thumbnail = dataStream.ToArray();
                    }
                }

                string htmlArticle = Markdown.ToHtml(model.Article);
                article.Article = htmlArticle;
                article.Title = model.Title;
                article.Description = model.Description;
                article.IsDraft = model.IsDraft;
                article.PublishDate = model.PublishDate;

                _authContext.Blogs.Update(article);
                await _authContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(model);
        }
    }
}

Controllers/IssuesController.cs
using LunarDev.Areas.Identity.Data;
using LunarDev.Data;
using LunarDev.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LunarDev.Controllers
{
    [Route("")]
    [Authorize]
    public class IssuesController : Controller
    {
        private readonly ILogger _logger;
        private readonly UserManager<AuthUser> _userManager;
        private readonly AuthContext _authContext;

        public IssuesController(ILogger<IssuesController> logger, UserManager<AuthUser> userManager, AuthContext authContext)
        {
            _logger = logger;
            _userManager = userManager;
            _authContext = authContext;
        }

        [Route("tracker")]
        public async Task<ActionResult> IndexAsync()
        {
            AuthUser user = await _userManager.GetUserAsync(User);

            var projects = new ProjectsIndexModel()
                .projects = _authContext.Projects.Include(x => x.Issues).Where(x => x.User.Id == user.Id).ToList();

            return View(projects);
        }

        [Route("projects/create")]
        [HttpPost]
        public async Task<ActionResult> ProjectCreate(ProjectsModel model)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                model.UserId = user.Id;

                if (Request.Form.Files.Count > 0)
                {
                    IFormFile file = Request.Form.Files.FirstOrDefault();
                    using (var dataStream = new MemoryStream())
                    {
                        await file.CopyToAsync(dataStream);
                        model.Icon = dataStream.ToArray();
                    }
                }

                _authContext.Projects.Add(model);
                _authContext.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                ErrorViewModel error = new ErrorViewModel();
                return View("Error", error);
            }
        }

        [Route("projects/edit")]
        [HttpPost]
        public async Task<ActionResult> ProjectEdit(ProjectsModel model)
        {
            var project = await _authContext.Projects.FindAsync(model.Id);
            try
            {
                if (Request.Form.Files.Count > 0)
                {
                    IFormFile file = Request.Form.Files.FirstOrDefault();
                    using (var dataStream = new MemoryStream())
                    {
                        await file.CopyToAsync(dataStream);
                        project.Icon = dataStream.ToArray();
                    }
                }

                project.Title = model.Title;
                project.Description = model.Description;

                _authContext.Projects.Update(project);
                _authContext.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.Write(ex.ToString());
                var error = new ErrorViewModel()
                    .RequestId = "500";
                return RedirectToAction("Index");
            }
        }

        [Route("projects/delete")]
        [HttpPost]
        public async Task<ActionResult> ProjectDelete(int id)
        {
            var model = _authContext.Projects.Find(id);
            var curUserId = (await _userManager.GetUserAsync(User)).Id;
            if (model.User.Id == curUserId)
            {
                _authContext.Projects.Remove(model);
                _authContext.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [Route("issues/")]
        [HttpGet]
        public ActionResult IssueList(int projectId)
        {
            if (projectId == 0) return RedirectToAction("Index");

            var issueModel = _authContext.Issues
                .Include(x => x.Project)
                .Where(x => x.ProjectId == projectId).ToList();

            return View(issueModel);
        }

        [Route("issues/edit")]
        [HttpPost]
        public async Task<ActionResult> IssueEdit(IssuesModel model)
        {
            try
            {
                _authContext.Issues.Update(model);
                _authContext.SaveChanges();
                return RedirectToAction("IssueList", new { projectId=model.ProjectId});
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return View("Error", new ErrorViewModel());
            }
        }

        [Route("issues/boardChange")]
        [HttpPost]
        public async Task<ActionResult> IssueBoardChange(int Id, string Board)
        {
            try
            {
                var model = await _authContext.Issues.FindAsync(Id);
                switch (Board) {
                    case "_todo":
                        model.Status = IssueStatus.Todo;
                        break;
                    case "_working":
                        model.Status = IssueStatus.Progress;
                        break;
                    case "_solved":
                        model.Status = IssueStatus.Solved;
                        break;
                    case "_canceled":
                        model.Status = IssueStatus.Canceled;
                        break;
                }
                _authContext.Issues.Update(model);
                _authContext.SaveChanges();
                return RedirectToAction("IssueList", new { projectId=model.ProjectId});
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return View("Error", new ErrorViewModel());
            }
        }

        [Route("issues/create")]
        [HttpPost]
        public async Task<ActionResult> IssueCreate(IssuesModel model)
        {
            try
            {
                model.Status = IssueStatus.Todo;
                _authContext.Issues.Add(model);
                _authContext.SaveChanges();
                return RedirectToAction("IssueList", new { projectId = model.ProjectId });
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return View("Error", new ErrorViewModel());
            }
        }

        [Route("issues/delete")]
        public async Task<ActionResult> IssueDelete(int id)
        {
            var issue = _authContext.Issues
                .Include(x => x.Project)
                .Where(x => x.Id == id)
                .ToList().First();

            var projectId = issue.ProjectId;
            var project = _authContext.Projects
                .Include(x => x.User)
                .FirstOrDefault(x => x.Id == projectId);

            var curUserId = (await _userManager.GetUserAsync(User)).Id;
            if (project.User.Id == curUserId)
            {
                _authContext.Issues.Remove(issue);
                _authContext.SaveChanges();
            }

            return RedirectToAction("IssueList", new { projectId = projectId });
        }
    }
}

Views/Issues/Index.cshtml
@model IEnumerable<LunarDev.Models.ProjectsModel>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Tracker";
}

<section class="text-dark">
    <div class="text-center">
        <h2>Projects</h2>
    </div>

    <hr class="horizontal" />

    <div class="row row-cols-3">

    @{
        foreach (ProjectsModel project in Model)
        {
            <div class="col mb-4">
                <div class="card">
                    <div class="card-body p-3">
                    <div class="d-flex">
                        <div class="avatar avatar-xl bg-dark border-radius-md p-2">
                            <img style="object-fit:contain; max-width:60px; max-height:60px;" src="data:image/*;base64,@(Convert.ToBase64String(project.Icon))">
                        </div>
                        <div class="ms-3 my-auto">
                            <h6>@project.Title</h6>
                        </div>
                        <div class="ms-auto">
                            <div class="dropdown">
                                <button class="btn btn-link text-secondary ps-0 pe-2" id="ActionMenu" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-ellipsis-v text-lg"></i>
                                </button>
                                <div class="dropdown-menu ms-n4" aria-labelledby="ActionMenu">
                                    <a class="dropdown-item" asp-action="IssueList" asp-route-projectId=@project.Id>View</a>
                                    <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#Edit-@project.Id">Edit</a>
                                    <a class="dropdown-item text-danger" href="#" data-bs-toggle="modal" data-bs-target="#Delete-@project.Id">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <p class="text-sm mt-3"> @project.Description </p>
                    <hr class="horizontal dark">
                    <div class="row">
                        <div class="col-6">
                        <h6 class="text-sm mb-0">@project.Issues.Count()</h6>
                        <p class="text-secondary text-sm font-weight-bold mb-0">Issues</p>
                        </div>
                        <div class="col-6 text-end">
                        <h6 class="text-sm mb-0">@project.CreatedDate.ToShortDateString()</h6>
                        <p class="text-secondary text-sm font-weight-bold mb-0">Started date</p>
                        </div>
                    </div>
                    </div>
                </div>
            </div>

            <!-- Modal -->
            <partial name="ProjectEditPartial" model="project"/>
            <partial name="ProjectDeletePartial" model="project"/>
            
        }
    }
    <div class="col mb-4">
        <div class="card h-100">
          <div class="card-body d-flex flex-column justify-content-center text-center">
            <a href="#" data-bs-toggle="modal" data-bs-target="#CreateProject">
              <i class="fa fa-plus text-secondary mb-3"></i>
              <h5 class=" text-secondary"> New project </h5>
            </a>
          </div>
        </div>
        <!-- Modal -->
        <partial name="ProjectCreatePartial" model="new ProjectsModel();"/>
        
      </div>
    </div>
    
</section>

Views/Issues/IssueCreatePartial.cshtml
@model LunarDev.Models.IssuesModel

@{
    ViewData["Title"] = "ProjectEdit";

    var queryString = this.Context.Request.Query.FirstOrDefault(x => x.Key.Equals("projectId")).Value;
}

<div class="modal fade" id="IssueCreate" tabindex="-1" role="dialog" aria-labelledby="IssueCreate" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <form enctype="multipart/form-data" asp-action="IssueCreate">
            <div class="modal-header">
            <h5 class="modal-title" id="IssueCreate">Create new Issue</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
            <div class="row">
                <input type="hidden" asp-for="ProjectId"/>
                <div class="col-12">
        
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" required/>
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group">
                        <label asp-for="Issue" class="control-label"></label>
                        <textarea asp-for="Issue" class="form-control" required></textarea>
                        <span asp-validation-for="Issue" class="text-danger"></span>
                    </div>
                </div>
            </div>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn bg-gradient-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn bg-gradient-primary">Save changes</button>
            </div>
        </form>
    </div>
    </div>
</div>

Views/Issues/IssueDeletePartial.cshtml
@model LunarDev.Models.IssuesModel

@{
    ViewData["Title"] = "ProjectEdit";

    var queryString = this.Context.Request.Query.FirstOrDefault(x => x.Key.Equals("projectId")).Value;
}

<div class="modal fade" id="Delete-@Model.Id" tabindex="-1" role="dialog" aria-labelledby="Delete-@Model.Id" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <form enctype="multipart/form-data" asp-action="IssueDelete" asp-route-id="@Model.Id" id="DeleteForm-@Model.Id">
            <div class="modal-header">
            <h5 class="modal-title" id="Delete-@Model.Id-Title">Delete '@Model.Title?'</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                <div class="text-center">
                        <h6>Are you sure you want to delete this project?</h6>
                        <code class="text-danger">Once deleted there will be no way to get it back.</code>
                    </div>
                <div class="modal-footer">
                <button type="button" class="btn bg-gradient-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn bg-gradient-primary">Confirm</button>
                </div>
            </div>
        </form>
    </div>
    </div>
</div>

<script>
    $("#DeleteForm-@Model.Id").submit(function(e) {
        e.preventDefault();

        var form = $(this);
        var actionUrl = form.attr('action');

        $.ajax({
            type: "POST",
            url: actionUrl,
            data: form.serialize(),
            success: function(data){
                Kanban.removeElement('@Model.Id');
                $("#Delete-@Model.Id").modal('hide');
            }
        })
    });
</script>

Views/Issues/IssueEditPartial.cshtml
@model LunarDev.Models.IssuesModel

@{
    ViewData["Title"] = "ProjectEdit";

    var queryString = this.Context.Request.Query.FirstOrDefault(x => x.Key.Equals("projectId")).Value;
}

<div class="modal fade" id="Edit-@Model.Id" tabindex="-1" role="dialog" aria-labelledby="Edit-@Model.Id" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form enctype="multipart/form-data" asp-action="IssueEdit" id="EditForm-@Model.Id">
                <div class="modal-header">
                    <h5 class="modal-title" id="Edit-@Model.Id-Title">Edit '@Model.Title'</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-12">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="Id" />
                            <input type="hidden" asp-for="ProjectId"/>
                            <div class="form-group">
                                <label asp-for="Title" class="control-label"></label>
                                <input asp-for="Title" class="form-control" required/>
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <label asp-for="Issue" class="control-label"></label>
                                <textarea asp-for="Issue" class="form-control" required></textarea>
                                <span asp-validation-for="Issue" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn bg-gradient-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn bg-gradient-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    $("#EditForm-@Model.Id").submit(function(e) {
        e.preventDefault();

        var form = $(this);
        var title = form.find("#Title");
        var issue = form.find("#Issue");
        var actionUrl = form.attr('action');

        $.ajax({
            type: "POST",
            url: actionUrl,
            data: form.serialize(),
            success: function(data){
                Kanban.findElement(@Model.Id).innerHTML = title.val();
                $("#View-@Model.Id").find("#Title").val(title.val());
                $("#View-@Model.Id").find("#Issue").val(issue.val());
                $("#View-@Model.Id-Title").text(title.val());
                $("#Edit-@Model.Id").modal('hide')
                $("#Edit-@Model.Id-Title").text("Edit '"+title.val()+"'");
                $("#Delete-@Model.Id-Title").text("Delete '"+title.val()+"'?");
            }
        })

    });

</script>

Views/Issues/IssueViewPartial.cshtml
@model LunarDev.Models.IssuesModel

@{
    ViewData["Title"] = "ProjectEdit";

    var queryString = this.Context.Request.Query.FirstOrDefault(x => x.Key.Equals("projectId")).Value;
}

<div class="modal fade" id="View-@Model.Id" tabindex="-1" role="dialog" aria-labelledby="Views-@Model.Id" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <form enctype="multipart/form-data" asp-action="IssueEdit">
            <div class="modal-header">
            <h5 class="modal-title" id="View-@Model.Id-Title">View @Model.Title</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
            <div class="row">
                <div class="col-12">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <input type="hidden" asp-for="ProjectId"/>
                    <div class="form-group disabled">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" disabled/>
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group disabled">
                        <label asp-for="Issue" class="control-label"></label>
                        <textarea asp-for="Issue" class="form-control" disabled></textarea>
                        <span asp-validation-for="Issue" class="text-danger"></span>
                    </div>
                </div>
            </div>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn bg-gradient-primary" onclick="ViewEditClick(@Model.Id)">Edit</button>
            <button type="button" class="btn bg-gradient-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn bg-gradient-danger" onclick="ViewDeleteClick(@Model.Id)">Delete</button>
            </div>
        </form>
    </div>
    </div>
</div>

Views/Issues/ProjectDeletePartial.cshtml
@model LunarDev.Models.ProjectsModel

<div class="modal fade" id="Delete-@Model.Id" tabindex="-1" role="dialog" aria-labelledby="Delete-@Model.Id" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form enctype="multipart/form-data" asp-action="ProjectDelete" asp-route-id="@Model.Id">
                <div class="modal-header">
                    <h5 class="modal-title" id="Delete-@Model.Id">Delete @Model.Title?</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="text-center">
                        <h6>Are you sure you want to delete this project?</h6>
                        <code class="text-danger">Once deleted there will be no way to get it back.</code>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn bg-gradient-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn bg-gradient-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Issues/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="@ViewData["Desc"]" />

    <title>@ViewData["Title"] - LunarDev</title>

    <!--Page specific css-->
    @RenderSection("Style", false)

    <!--Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet">

    <!--Icons-->
    <link rel="stylesheet" href="~/css/nucleo-icons.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/nucleo-svg.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/d8ef3bbe55.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

    <!--Css-->
    <link rel="stylesheet" href="~/css/now-design-system-pro.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

</head>
<body class="bg-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container position-relative">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                  Lunar Development
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon mt-2">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                  </span>
                </button>
                <div class="collapse navbar-collapse w-100 pt-3 pb-2 py-lg-0" id="navigation">
                  <ul class="navbar-nav navbar-nav-hover mx-auto position-absolute start-50 translate-middle-x">
                    <li class="nav-item px-3">
                      <a class="nav-link" asp-controller="Home" asp-action="Index">
                        Home
                      </a>
                    </li>

                    <li class="nav-item px-3">
                      <a class="nav-link" asp-controller="Home" asp-action="About">
                        About
                      </a>
                    </li>

                    <li class="nav-item px-3">
                      <a class="nav-link" asp-controller="Issues" asp-action="Index">
                        Issue Tracker
                      </a>
                    </li>

                    <li class="nav-item px-3">
                      <a class="nav-link" asp-controller="Blog" asp-action="Index">
                        Blog
                      </a>
                    </li>
                  </ul>
                  
                  <ul class="navbar-nav position-absolute end-0">
                    <partial name="~/Views/Shared/_LoginPartial.cshtml" />
                  </ul>

                </div>
              </div>
            </nav>
    </header>

    <main role="main">
        @RenderBody()
    </main>

    <div class="position-absolute bottom-0 w-100 mt-6 d-none d-sm-block">
        <footer class="border-top footer mb-3">
            <div class="container pt-2">
                &copy; 2022 - Lunar-Dev - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="link-dark">Privacy</a>
            </div>
        </footer>
    </div>

    <!-- Core -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/material/core/popper.min.js"></script>

    <!-- Theme JS -->
    <script src="~/js/now-design-system-pro.min.js" type="text/javascript"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>